$PROJ_ROOT/src_new/rcu/unit/counter/counter.v
$PROJ_ROOT/$COMMONCELL_ROOT/counter2.v
$PROJ_ROOT/src_new/rcu/unit/oldest2_abitter/arbiter_base.v
$PROJ_ROOT/$COMMONCELL_ROOT/src/Queue/hw/FIFO/MultiPortStreamFIFO.v
$PROJ_ROOT/src_new/lsuv1/lsu_agu.v
$PROJ_ROOT/src_new/lsuv1/lsu_bus_ctrl.v
$PROJ_ROOT/src_new/lsuv1/lsu_mc.v
$PROJ_ROOT/src_new/lsuv1/lsu_pma_checker.v
$PROJ_ROOT/src_new/lsuv1/lsu_wb_arb.v
$PROJ_ROOT/src_new/lsuv1/lsu_lsq_entry.v
$PROJ_ROOT/src_new/lsuv1/lsu_lsq.v
$PROJ_ROOT/src_new/lsuv1/lsuv1.v